### ISSUE TITLE
Remove CommentWarningDialog

### ISSUE THREAD

**Issue by Olgabrezel** [CrazyPokemonDev/WuffPad#1]
Commens won't be deleted anymore (if you didn't lie at us 🤣 )

**Comment by Olfi01** [comment]
Yes, but as of lazyness i just set the standard setting of doNotShowWarningAgain to true😂

**Comment by Olfi01** [comment]
*laziness ofc

**Comment by Olfi01** [comment]
If you wanna remove it, go on :P

**Comment by Olfi01** [comment]
i removed it 82dc7aa
