### ISSUE TITLE
When a content is deleted the Value column is not updated with the correct count

### ISSUE THREAD

**Issue by FernandoTBarros** [CrazyPokemonDev/WuffPad#2]

**Comment by Olfi01** [comment]
Thanks to your report i have looked at it again and found a solution. Fixed! 
05610e2

**Comment by FernandoTBarros** [comment]
Great! It happens when adding new contents too, I don't know if the logic is in the same place but maybe listening to the size of the content will do the work.

**Comment by Olfi01** [comment]
I tried to do what you said first, but since it didnt work, I now just refresh the view manually
