### ISSUE TITLE
When a deprecated string is deleted it still complains when trying to save

### ISSUE THREAD

**Issue by FernandoTBarros** [CrazyPokemonDev/WuffPad#3]
I guess the correct is save disregarding the deprecated string.

**Comment by Olfi01** [comment]
What string do you mean? I'll look into it later
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit 1&1 Mail gesendet.Am 17.06.2017, 03:03, Fernando Teixeira Barros <notifications@github.com> schrieb:
I guess the correct is save disregarding the deprecated string.

**Comment by Olfi01** [comment]
Found them, fixed.
